### ISSUE TITLE
Raspberry Pi Tracking Normalization

### ISSUE THREAD

**Issue by madfrog54321** [USU-Robosub/Poseidon#168]
## Summary

The Raspberry Pi currently returns the location of an object as the location on a 640x480 grid. The values go from -320 to 320 and -240 to 240. The value should be normalized to a standard coordinate system. 
## Acceptance Criteria
- [ ] A normalized range needs to be decided upon.
- [ ] When the Pi returns a location it should be normalized to a specific range and should not be dependent on the camera's setup.
- [ ] Other code relying on the image tracking system needs to be updated.
## Non-functional Criteria

An example is to go from 0 to 1 in both directions. The problem with going from 0 to 1 is that the lens of the camera may effect how the gate looks from the sub.

**Comment by nfcopier** [comment]
:+1:
